### ISSUE TITLE
sudo: podman: command not found

### ISSUE THREAD

**Issue by sl-commits** [CodeSparta/devkit-vpc#16]
bash tools/dev.sh

**Then run this:**
./devkit-build-vpc.sh -vv -e aws_access_key=xxxxxxxxxxxxx -e aws_secret_key=XXXXXXXXXXXXXXXXX -e aws_cloud_region=us-gov-west-1
**And get the following error:**
sudo: podman: command not found

**podman is not installed**
find / -name podman
/usr/local/lib/python3.6/site-packages/ansible_collections/containers/podman
/usr/local/lib/python3.6/site-packages/ansible_collections/containers/podman/plugins/module_utils/podman

**Comment by usrbinkat** [comment]
per docs, please supply podman as a prerequisite.
