### ISSUE TITLE
Konductor teraform verfiy  -var-file error

### ISSUE THREAD

**Issue by ltratcliff** [CodeSparta/devkit-vpc#21]
Getting: "Flag provided, but not defined"

![image](https://user-images.githubusercontent.com/9104793/115445598-0e550380-a1e4-11eb-8a62-bce7a5fc76fb.png)

**Comment by ltratcliff** [comment]
Worked around error by using Konductor:4.7.5 (vs latest)

**Comment by ltratcliff** [comment]
Here's a better shot of the error:

![image](https://user-images.githubusercontent.com/9104793/115546879-8ddde380-a273-11eb-841d-d69d4a51a325.png)

**Comment by day0hero** [comment]
@ltratcliff thanks for reporting and sorry for slow reply!

**Comment by ltratcliff** [comment]
No worries! THanks for the help!!
